<a href="https://colab.research.google.com/github/Blackman9t/Machine_Learning/blob/master/coefficients_of_multiple_linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### <font color='khaki'>Getting to understand Multiple Linear Regression better by walking through it's internal workings and computation

In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Defining the scores table  like on the website

In [22]:
student_scores = pd.DataFrame({'Score':[100, 90, 80, 70, 60], 'IQ':[110, 120, 100, 90, 80,], 'Study_hours':[40, 30, 20, 0, 10]})

student_scores.index.name='Student'

student_scores.head()

Score   IQ  Study_hours
Student                         
0          100  110           40
1           90  120           30
2           80  100           20
3           70   90            0
4           60   80           10

## Defining Matrix X

In [23]:
X = student_scores.loc[:, ['IQ',"Study_hours"]]

ones = np.ones(len(student_scores), dtype=int)

X.insert(0, 'ones', ones)

X.head()

ones   IQ  Study_hours
Student                        
0           1  110           40
1           1  120           30
2           1  100           20
3           1   90            0
4           1   80           10

In [24]:
# Next we convert X to a Numpy array from a Data frame

X = X.values

X

array([[  1, 110,  40],
       [  1, 120,  30],
       [  1, 100,  20],
       [  1,  90,   0],
       [  1,  80,  10]])

## Defining X' or X Transpose

In [25]:
X_tp = X.transpose()

X_tp

array([[  1,   1,   1,   1,   1],
       [110, 120, 100,  90,  80],
       [ 40,  30,  20,   0,  10]])

#### Print out the shape of X and X'.

In [26]:
print('X shape is',X.shape,'\nX-tanspose shape is',X_tp.shape)

X shape is (5, 3) 
X-tanspose shape is (3, 5)


## Define X' by X... using matrix multiplication

In [27]:
X_tp_X = np.matmul(X_tp, X)

X_tp_X

array([[    5,   500,   100],
       [  500, 51000, 10800],
       [  100, 10800,  3000]])

Notice,  that so far we are getting exactly the same result as on the website [stattrek.com](https://stattrek.com/multiple-regression/regression-coefficients.aspx?Tutorial=reg)

## Next we define the inverse of X'X, just like in the website

In [29]:
from numpy.linalg import inv

inverse = inv(X_tp_X)

inverse

array([[ 2.02000000e+01, -2.33333333e-01,  1.66666667e-01],
       [-2.33333333e-01,  2.77777778e-03, -2.22222222e-03],
       [ 1.66666667e-01, -2.22222222e-03,  2.77777778e-03]])

In [31]:
# checking to make sure the same values as the website

print(inverse[0,:])
print(inverse[1,:])
print(inverse[2,:])

[20.2        -0.23333333  0.16666667]
[-0.23333333  0.00277778 -0.00222222]
[ 0.16666667 -0.00222222  0.00277778]


everything is perfect up to this point

## Next we define the Y variable

In [33]:
Y = student_scores.Score

Y.values

array([100,  90,  80,  70,  60])

## Calculating the slope or coefficients

<h2><font color='khaki'>$ b = (X'X)^{-1}X'Y $</h2>

How do you compute this equation using matrix multiplication?

Please fill in the right code below or be nice to share your screen shot in any python terminal

In [37]:
b = np.matmul(inverse, X_tp)
z = np.matmul(b, Y)

ValueError: ignored